# Generated by Django 3.2.6 on 2021-11-10 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='product_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curation',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='curation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='curation.CurationTag'),
        ),
        migrations.AddField(
            model_name='curation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_curations', to=settings.AUTH_USER_MODEL),
        ),
    ]
