# Generated by Django 3.2.6 on 2021-11-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_curationcomment_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curationcomment',
            old_name='comment_user',
            new_name='user',
        ),
    ]
