version: "3"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - zipproject

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: "*"
    volumes:
      - build_folder:/frontend/build
    tty: true
    networks:
      - zipproject

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - zipproject


volumes:
  build_folder:

networks:
  zipproject:
    driver: bridge