# Generated by Django 3.2.6 on 2021-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('description', models.TextField(blank=True, default='', max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('comment_curation', models.ManyToManyField(blank=True, related_name='CommentCustomUser', to='curation.CurationComment')),
                ('created_curation', models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='curation.Curation')),
                ('created_product', models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='product.Product')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('like_curation', models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='curation.Curation')),
                ('like_product', models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='product.Product')),
                ('review_product', models.ManyToManyField(blank=True, related_name='ReviewCustomUser', to='product.ProductReview')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
