# Generated by Django 3.2.6 on 2021-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_tags', models.ManyToManyField(blank=True, to='curation.CurationTag')),
                ('curations', models.ManyToManyField(blank=True, to='curation.Curation')),
                ('product_tags', models.ManyToManyField(blank=True, to='product.ProductTag')),
                ('products', models.ManyToManyField(blank=True, related_name='rec_products', to='product.Product')),
            ],
        ),
    ]
